### ISSUE TITLE
Изменение состава JSON-ответа сервера

### ISSUE THREAD

**Issue by tr-NSergey** [itimofeev/hustledb-android#3]
Переименуй, пожалуйста, поле "class" на что-нибудь незарезервированное в java.

**Comment by itimofeev** [comment]
Поменял на dancer_class и разобрался, как задеплоить на сервер.

Можно весь список получить http://192.168.99.100:18080/api/v1/prereg/
Но более полезным будет метод  получения по id http://192.168.99.100:18080/api/v1/prereg/9
